version: "3.9"
services:
  browser:
    image: selenium/standalone-firefox
    environment:
      - SE_NODE_SESSION_TIMEOUT=300  # Timeout per la sessione
    deploy:
      placement:
        constraints:
          - node.role == manager
          - node.hostname != CB-Mass-Node1
    ports:
      - "45900:5900"  
    networks:
      - BIG-dataplatform-network

networks:
  BIG-dataplatform-network:
    external: true
    name: BIG-dataplatform-network
