version: "3.9"
services:
  spark-master:
    image: apache/spark:${SPARKVERSION}
    environment:
      - SPARK_NO_DAEMONIZE=true
    volumes:
      - spark_config:${SPARKCONFDIR}
      - hadoop_config:${HADOOPCONFDIR}
    ports:
      - ${SPARKMASTERPORT}:${SPARKMASTERPORT}
    command:
      - /bin/bash
      - -c
      - |
        cp -r ${HADOOPCONFDIR}* ${SPARKCONFDIR}
        /opt/spark/sbin/start-master.sh
    deploy:
      placement:
        constraints:
          - node.hostname != CB-Mass-Node1
    networks:
      - BIG-dataplatform-network 

  spark-worker:
    image: apache/spark:${SPARKVERSION}
    environment:
      - SPARK_NO_DAEMONIZE=true
    volumes:
      - spark_config:${SPARKCONFDIR}
      - hadoop_config:${HADOOPCONFDIR}
    command:
      - /bin/bash
      - -c
      - |
        cp -r ${HADOOPCONFDIR}* ${SPARKCONFDIR}
        /opt/spark/sbin/start-worker.sh spark://${SPARKMASTERHOST}:${SPARKMASTERPORT}
    deploy:
      placement:
        constraints:
          - node.hostname != CB-Mass-Node1
    networks:
      - BIG-dataplatform-network 

  spark-history-server:
    image: apache/spark:${SPARKVERSION}
    environment:
      - SPARK_NO_DAEMONIZE=true
    volumes:
      - spark_config:${SPARKCONFDIR}
      - hadoop_config:${HADOOPCONFDIR}
    ports:
      - ${SPARKHISTSERVERPORT}:${SPARKHISTSERVERPORT}
    command:
      - /bin/bash
      - -c
      - |
        mkdir -p tmp/spark-events/
        sudo chown spark tmp/spark-events/
        if [ ! -d tmp/spark-events/ ]; then
          echo "Spark logs data directory not found"
          exit 2
        fi
        cp -r ${HADOOPCONFDIR}* ${SPARKCONFDIR}
        /opt/spark/sbin/start-history-server.sh
    deploy:
      placement:
        constraints:
          - node.hostname != CB-Mass-Node1
    networks:
      - BIG-dataplatform-network
      
volumes:
  spark_config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFSADDRESS},rw,nfsvers=4,nolock,hard
      device: ":${NFSPATH}/dataplatform_config/spark_conf/"
        
  hadoop_config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFSADDRESS},rw,nfsvers=4,nolock,hard
      device: ":${NFSPATH}/dataplatform_config/hadoop_conf/"

networks:
  BIG-dataplatform-network:
    external: true
    name: BIG-dataplatform-network
