version: "3.9"
services:
  orion:
    init: true
    image: fiware/orion:3.10.1
    depends_on:
      - mongodb
    networks:
      - BIG-dataplatform-network
    ports:
      - "${FIWARE_PORT}:1026"
    command: -corsOrigin __ALL -dbhost mongodb -inReqPayloadMaxSize 5000000
    deploy:
      placement:
        constraints:
          - node.hostname != CB-Mass-Node1

  mongodb:
    init: true
    image: mongo:6.0
    ports:
      - "${MONGODB_PORT}:27017"
    networks:
      - BIG-dataplatform-network
    deploy:
      placement:
        constraints:
          - node.hostname != CB-Mass-Node1

  fileserver:
    init: true
    image: jetbrainsinfra/nginx-file-listing:0.2
    ports:
      - "${FILESERVER_PORT}:80"
    volumes:
      - pnrr-datalake-landing:/mnt/data
    networks:
      - BIG-dataplatform-network
    deploy:
      placement:
        constraints:
          - node.hostname != CB-Mass-Node1

  # mosquitto:
  #   init: true
  #   image: eclipse-mosquitto:2.0.11
  #   ports:
  #     - "${MOSQUITTO_PORT_EXT}:1883"
  #     - "${MOSQUITTO_PORT_EXT_TLS}:8883"
  #   volumes:
  #     - mqtt-volume/config:/mosquitto/config:ro
  #     - mqtt-volume/log:/mosquitto/log
  #     - mqtt-volume/data:/mosquitto/data
  #   networks:
  #     - BIG-dataplatform-network

  # etl:
  #   init: true
  #   hostname: etl
  #   image: ${SWARM_REGISTER_IP}:${SWARM_REGISTER_PORT}/etl
  #   build: ./etl
  #   ports:
  #     - "${DRACO_PORT_EXT}:${DRACO_PORT_EXT}"
  #   networks:
  #     - BIG-dataplatform-network
  #   healthcheck:
  #     test: |
  #       curl --fail -H 'Content-Type: application/json' -d '{"heartbeat": ""}' -s http://localhost:${DRACO_PORT_EXT}
  #     interval: 5s
  #     timeout: 10s

  # writetomongo:
  #   init: true
  #   hostname: writetomongo
  #   image: ${SWARM_REGISTER_IP}:${SWARM_REGISTER_PORT}/writetomongo
  #   build:
  #     context: ./devices
  #     dockerfile: writetomongo.Dockerfile
  #   networks:
  #     - BIG-dataplatform-network
  #   depends_on:
  #     - mongodb

  # ftp:
  #   init: true
  #   image: stilliard/pure-ftpd
  #   environment:
  #     FTP_USER_NAME: "${FTP_USER}"
  #     FTP_USER_PASS: "${FTP_PWD}"
  #     FTP_USER_HOME: "/data"
  #     FTP_PASSIVE_PORTS: "${FTP_PORT_MIN}:${FTP_PORT_MAX}"
  #     FTP_MAX_CLIENTS: 50
  #     FTP_MAX_CONNECTIONS: 20
  #     ADDED_FLAGS: "-d -d"
  #     PUBLICHOST: "${FTP_IP}"
  #   volumes:
  #     - ftp-volume:/data
  #   ports:
  #     - "${FTP_PORT_FTP20_EXT}:20"
  #     - "${FTP_PORT_FTP21_EXT}:21"
  #     - "${FTP_PORT_MIN}-${FTP_PORT_MAX}:${FTP_PORT_MIN}-${FTP_PORT_MAX}/tcp"
  #   networks:
  #     - BIG-dataplatform-network

volumes:

  # mqtt-volume:
  #   driver_opts:
  #     type: nfs
  #     o: addr=${NFSADDRESS},rw,nfsvers=4
  #     device: ":${NFSPATH}/mqtt-mosquitto/"

  ftp-volume:
    driver_opts:
      type: nfs
      o: addr=${NFSADDRESS},rw,nfsvers=4
      device: ":${NFSPATH}/ftp/"

  pnrr-datalake-landing:
    driver_opts:
      type: nfs
      o: addr=${NFSADDRESS},rw,nfsvers=4
      device: ":${NFSPATH}/pnrr_dataplatform/datalake/"

networks:
  BIG-dataplatform-network:
    external: true
    name: BIG-dataplatform-network
