version: '3.9'

services:
  hdfs-client:
    image: apache/hadoop:${HADOOPVERSION}
    volumes:
      - hadoop_config:${HADOOPCONFDIR}
    command:
      - /bin/bash
      - -c
      - |
        sleep 20
        sudo yum install -y openssh-clients
        hdfs dfs -get /geoserver-data . 2> /tmp/hdfs_error.log
        if [ $? -ne 0 ]; then
          echo "Error occurred while getting data from HDFS geoserver-data folder"
          exit 1
        fi
        echo "End to get data from HDFS geoserver-data folder"
        sleep 600
        count=0
        while ! ping -c 1 geoserver &> /dev/null && [ $count -lt 100000 ]; do
          echo "Geoserver container is not reachable, retrying in 10 seconds..."
          sleep 10
          count=$((count+1))
        done
        if [ $count -eq 100000 ]; then
          echo "Reached maximum retry limit, exiting..."
          exit 1
        fi
        echo "Geoserver container is reachable, proceeding with scp command"
        scp -r geoserver-data/data/* geoserver:/home/geoserver/data 2> /tmp/scp_error.log
        if [ $? -ne 0 ]; then
          echo "Error occurred while copying data to geoserver container"
          exit 1
        fi
        echo "End scp data to geoserver container"
    deploy:
      placement:
        constraints:
          - node.role != manager
          - node.hostname != CB-Mass-Node1
    networks:
      - BIG-dataplatform-network

  geoserver:
    image: docker.osgeo.org/geoserver:2.25.x
    environment:
      SKIP_DEMO_DATA: "true"
    networks:
      - BIG-dataplatform-network
    ports:
      - ${GEOSERVER_PORT}:8080
    volumes:
      - geoserver_data_dir:/opt/geoserver_data
    deploy:
      placement:
        constraints:
          - node.hostname != CB-Mass-Node1
          - node.role == worker

volumes:
  hadoop_config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFSADDRESS},rw,nfsvers=4,nolock,hard
      device: ":${NFSPATH}/dataplatform_config/hadoop_conf/"
  geoserver_data_dir:
    driver_opts:
      type: nfs
      o: addr=${NFSADDRESS},rw,nfsvers=4
      device: :${NFSPATH}/dataplatform_config/geoserver/data_dir
  #geoserver_conf:
  #  driver_opts:
  #    type: nfs
  #    o: addr=${NFSADDRESS},rw,nfsvers=4
  #    device: :${NFSPATH}/dataplatform_config/geoserver_conf/

networks:
  BIG-dataplatform-network:
    external: true
    name: BIG-dataplatform-network
