version: '3.9'

services:
  geoserver:
    image: 127.0.0.0:5000/geoserver_hdfs:v0.0.1
    environment:
      SKIP_DEMO_DATA: "true"
      GEOSERVER_CSRF_DISABLE: "false"
      GEOSERVER_CSRF_WHITELIST: 'big.csr.unibo.it'
    networks:
      - BIG-dataplatform-network
    ports:
      - ${GEOSERVER_PORT}:8080
    volumes:
      - geoserver_data_dir:/opt/geoserver_data
      - geoserver_data:/home/geoserver/data
      - hadoop_config:/usr/local/hadoop/etc/hadoop
    deploy:
      placement:
        constraints:
          - node.hostname != CB-Mass-Node1
          - node.role == manager

volumes:
  geoserver_data:
    driver_opts:
      type: nfs
      o: addr=${NFSADDRESS},rw,nfsvers=4
      device: :${NFSPATH}/dataplatform_config/geoserver/data
  geoserver_data_dir:
    driver_opts:
      type: nfs
      o: addr=${NFSADDRESS},rw,nfsvers=4
      device: :${NFSPATH}/dataplatform_config/geoserver/data_dir
  hadoop_config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFSADDRESS},rw,nfsvers=4,nolock,hard
      device: :${NFSPATH}/dataplatform_config/hadoop_conf/

  #geoserver_conf:
  #  driver_opts:
  #    type: nfs
  #    o: addr=${NFSADDRESS},rw,nfsvers=4
  #    device: :${NFSPATH}/dataplatform_config/geoserver_conf/

networks:
  BIG-dataplatform-network:
    external: true
    name: BIG-dataplatform-network
