version: "3.9"
services:
  hdfs-client:
    image: apache/hadoop:${HADOOPVERSION}
    volumes:
      - hadoop_config:${HADOOPCONFDIR}
      - hdfs_bridge:/home/hdfs_bridge
    command: ["tail", "-f", "/dev/null"]
    stdin_open: true
    tty: true
    deploy:
      placement:
        constraints:
          - node.role != manager
          - node.hostname == isi-bigcluster-pnnr-11
    networks:
      - BIG-dataplatform-network

volumes:
  hadoop_config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFSADDRESS},rw,nfsvers=4,nolock,hard
      device: ":${NFSPATH}/dataplatform_config/hadoop_conf/"

  hdfs_bridge:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFSADDRESS},rw,nfsvers=4,nolock,hard
      device: ":${NFSPATH}/hdfs_bridge/"

networks:
  BIG-dataplatform-network:
    external: true
    name: BIG-dataplatform-network
