version: '3'

services:
  hue:
      image: gethue/hue:latest
      ports:
      - "8888:8888"
  database:
      image: mysql:5.7
      ports:
          - "33061:3306"
      command: --init-file /data/application/init.sql
      environment:
          MYSQL_ROOT_USER: root
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: hue
          MYSQL_USER: test
          MYSQL_PASSWORD: test23
