version: '3.9'

services:
  hue:
      image: gethue/hue:latest
      ports:
        - ${HUEPORT}:8888
      volumes:
        - hadoop_config:${HADOOPCONFDIR}
        - hue_config:${HUECONFDIR}
      environment:
        HADOOP_CONF_DIR: /opt/hadoop/etc/hadoop/
      deploy:
        placement:
          constraints:
            - node.hostname != CB-Mass-Node1
      networks:
        - BIG-dataplatform-network 

volumes:
  hadoop_config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFSADDRESS},rw,nfsvers=4,nolock,hard
      device: ":${NFSPATH}/dataplatform_config/hadoop_conf/"

  hue_config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFSADDRESS},rw,nfsvers=4,nolock,hard
      device: ":${NFSPATH}/dataplatform_config/hue_conf/"

networks:
  BIG-dataplatform-network:
    external: true
    name: BIG-dataplatform-network
