version: "3.9"
services:
  kafka:
    image: docker.io/bitnami/kafka:3.7
    ports:
      - ${KAFKA_PORT_EXT}:49092
    environment:
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:9092,EXTERNAL_SAME_HOST://0.0.0.0:49092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://${KAFKA_IP}:49092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zoo1:2181,zoo2:2181,zoo3:2181
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    volumes:
      - kafka_data:/bitnami/
    deploy:
      placement:
        constraints:
          - node.role == manager 
    networks:
      - BIG-dataplatform-network

volumes:
  spark_config:
    driver_opts:
      type: nfs
      o: addr=${NFSADDRESS},rw,nfsvers=4
      device: ":${NFSPATH}/dataplatform_config/spark_conf/"
        
  hadoop_config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFSADDRESS},rw,nfsvers=4,nolock,hard
      device: ":${NFSPATH}/dataplatform_config/hadoop_conf/"

  kafka_data:
    driver_opts:
      type: nfs
      o: addr=${NFSADDRESS},rw,nfsvers=4
      device: ":${NFSPATH}/dataplatform_config/kafka_data/"

networks:
  BIG-dataplatform-network:
    external: true
    name: BIG-dataplatform-network
