version: "3.9"
services:
  sftp:
    image: atmoz/sftp
    volumes:
      - pnrr_datalake:/home/
      - host_keys:/etc/ssh/
    ports:
      - ${SFTPPORT}:22
    command: mpasini:pass:1001
    deploy:
      placement:
        constraints:
          - node.hostname != CB-Mass-Node1
    networks:
      - BIG-dataplatform-network         

volumes:
  pnrr_datalake:
    driver_opts:
      type: nfs
      o: addr=${NFSADDRESS},rw,nfsvers=4,nolock,hard
      device: ":${NFSPATH}/pnrr_datalake/"
      
  host_keys:
    driver_opts:
      type: nfs
      o: addr=${NFSADDRESS},rw,nfsvers=4,nolock,hard
      device: ":${NFSPATH}/dataplatform_config/sftp_hostkeys/"
        
networks:
  BIG-dataplatform-network:
    external: true
    name: BIG-dataplatform-network
