
services:
  tomcat:
    image: tomcat:9.0.102
    ports:
      - "${TOMCAT_FILESERVER_PORT}:8080"
    volumes:
      - tomcat-webapps:/usr/local/tomcat/webapps
    deploy:
      placement:
        constraints:
          - node.hostname != CB-Mass-Node1    

volumes:
  tomcat-webapps:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFSADDRESS},rw,nfsvers=4,nolock,hard
      device: ":${NFSPATH}/tomcat/tomcat9-webapps/"
