version: "3.9"
services:
  resourcemanager:
    image: apache/hadoop:${HADOOPVERSION}
    ports:
      - ${RESOURCEMANAGERPORT}:${RESOURCEMANAGERPORT}
    volumes:
      - hadoop_config:${HADOOPCONFDIR}
    command: 
      - /bin/bash
      - -c
      - |
        /opt/hadoop/bin/yarn --config /opt/hadoop/etc/hadoop resourcemanager
    deploy:
      placement:
        constraints:
          - node.role == manager
          - node.hostname != CB-Mass-Node1
    networks:
      - BIG-dataplatform-network 

  nodemanager:
    image: apache/hadoop:${HADOOPVERSION}
    volumes:
      - hadoop_config:${HADOOPCONFDIR}
    command:
      - /bin/bash
      - -c
      - |
        /opt/hadoop/bin/yarn --config /opt/hadoop/etc/hadoop nodemanager
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname != CB-Mass-Node1
    networks:
      - BIG-dataplatform-network 

  historyserver:
    image: apache/hadoop:${HADOOPVERSION}
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
      - hadoop_config:${HADOOPCONFDIR}
    ports:
      - ${YARNHISTSERVERPORT}:${YARNHISTSERVERPORT}
    command:
      - /bin/bash
      - -c
      - |
        mkdir -p /hadoop/yarn/timeline
        sudo chown hadoop /hadoop/yarn/timeline
        /opt/hadoop/bin/yarn --config /opt/hadoop/etc/hadoop historyserver
    deploy:
      placement:
        constraints:
          - node.role == worker
          - node.hostname != CB-Mass-Node1
    networks:
      - BIG-dataplatform-network 

volumes:
  hadoop_historyserver:
    driver_opts:
      type: nfs
      o: addr=${NFSADDRESS},rw,nfsvers=4
      device: :${NFSPATH}/dataplatform_config/yarn_hist_server_data/

  hadoop_config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFSADDRESS},rw,nfsvers=4,nolock,hard
      device: ":${NFSPATH}/dataplatform_config/hadoop_conf/"

networks:
  BIG-dataplatform-network:
    external: true
    name: BIG-dataplatform-network
