version: "3.9"
services:
  resourcemanager:
    image: apache/hadoop:3.3.6
    ports:
      - 8088:8088
    volumes:
      - hadoop_config:/opt/hadoop/etc/hadoop/
    command: 
      - /bin/bash
      - -c
      - |
        /opt/hadoop/bin/yarn --config /opt/hadoop/etc/hadoop resourcemanager
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - BIG-dataplatform-network 

  nodemanager:
    image: apache/hadoop:3.3.6
    volumes:
      - hadoop_config:/opt/hadoop/etc/hadoop/
    command:
      - /bin/bash
      - -c
      - |
        /opt/hadoop/bin/yarn --config /opt/hadoop/etc/hadoop nodemanager
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    networks:
      - BIG-dataplatform-network 

  historyserver:
    image: apache/hadoop:3.3.6
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
      - hadoop_config:/opt/hadoop/etc/hadoop/
    ports:
      - 19888:19888
    command:
      - /bin/bash
      - -c
      - |
        mkdir -p /hadoop/yarn/timeline
        sudo chown hadoop /hadoop/yarn/timeline
        /opt/hadoop/bin/yarn --config /opt/hadoop/etc/hadoop historyserver
    deploy:
      placement:
        constraints:
          - node.role == worker
    networks:
      - BIG-dataplatform-network 

volumes:
  hadoop_historyserver:
    driver_opts:
      type: nfs
      o: addr=137.204.74.55,rw,nfsvers=4
      device: :/mnt/mysharednfs/dataplatform/yarn_hist_server_data/

  hadoop_config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=137.204.74.55,rw,nfsvers=4,nolock,hard
      device: ":/mnt/mysharednfs/dataplatform/hadoop_conf/"

networks:
  BIG-dataplatform-network:
    external: true
    name: BIG-dataplatform-network