name: "gen-doc"
on:
  push:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Generate the slides
        run: |
          cd doc
          sudo apt-get install pandoc
          for f in *.md; 
            do echo "Processing $f file...";
            pandoc -t revealjs -s --mathjax=https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js -s -o $f.html $f -V revealjs-url=https://unpkg.com/reveal.js@3.9.2/ --include-in-header=slides.css -V theme=white --slide-level 2
          done
          mkdir _site
          mv *.html _site
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: _site
